title: resume | Kim Seong Ho # Curriculum Vitae
description:  
url: 
baseurl: ''
theme_skin: black

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
